# Exeption handling is called finally block execution
# It consist of three stages
# 1.try
# 2.except
# 3.finally
def add(n1,n2):
    try:
        print(n1/n2)
    except:

        print("exception")
add(1,0)